/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

/**
 *
 * @author Chad Chapman, Keegan Kell, hui ting cai, Hanan J Abdo 
 */
public class LoginPanel extends java.awt.Frame {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() 
    {
        initComponents();
        choice1.addItem("Student");
        choice1.addItem("Admin");
        choice1.addItem("Employer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label3 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        button1 = new java.awt.Button();

        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 400, 500));
        setLocationRelativeTo(this);
        setPreferredSize(new java.awt.Dimension(511, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        label1.setText("Internship Portal");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 511, -1));

        label2.setText("Login As");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, 20));
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 290, -1));

        label3.setText("ID");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 20));
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 290, -1));

        button1.setLabel("Login");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        Login(choice1.getSelectedIndex());
    }//GEN-LAST:event_button1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPanel().setVisible(true);
            }
        });
    }
    
    void Login(int idx) 
    {
        switch (idx) {
            case 0:
                System.out.println("Logged in as Student.");
                try 
                {
                    StudentPortalForm panel = new StudentPortalForm();
                    panel.setVisible(true);
                    this.dispose();
                } 
                catch (Exception e) 
                {
                    e.printStackTrace();
                }
                break;
            case 1:
                System.out.println("Logged in as Admin.");
                AdminPanel panel = new AdminPanel();
                panel.setVisible(true);
                this.dispose();
                break;
            case 2:
                System.out.println("Logged in as Employer.");
                break;
            default:
                break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
