/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

/**
 *
 * @author Chad Chapman, Keegan Kell, hui ting cai, Hanan J Abdo 
 */
public class StudentPortalForm extends java.awt.Frame {

    /**
     * Creates new form StudentPortalForm
     */
    public StudentPortalForm() {
        initComponents();
        panel1.setVisible(false);
        list1.add("Internship 1");
        list1.add("Internship 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        list1 = new java.awt.List();
        label2 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        textArea1 = new java.awt.TextArea();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(718, 560));
        setTitle("Student Portal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label1.setText("Student Portal");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, -1));

        list1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list1ItemStateChanged(evt);
            }
        });
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 410));

        label2.setText("Available Internships");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        panel1.setBackground(new java.awt.Color(153, 153, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 390, 200));

        button1.setLabel("Write Review");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        panel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        button2.setLabel("Mark as Interested");
        panel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 410, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
        try {
            LoginPanel frame = new LoginPanel();
            frame.setVisible(true);
            frame.setTitle("Login");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_exitForm

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        try
        {
            WriteReviewForm form = new WriteReviewForm();
            form.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_button1MouseClicked

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_list1ActionPerformed

    private void list1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list1ItemStateChanged
        // TODO add your handling code here:
        // System.out.println("List Index is " + list1.getSelectedIndex());
        panel1.setVisible(true);
        textArea1.setText(list1.getSelectedItem());
    }//GEN-LAST:event_list1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPortalForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.List list1;
    private java.awt.Panel panel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
